[Feat] Create list page
United-Devs/msn-client pull request #7
Opened 2023-02-07 01:17 UTC by milealmeida

- Create page list;
- Create status;
- Create MyProfile;

2023-02-07 09:22 UTC, iamdevmarcos requested changes

2023-02-07 09:22 UTC, iamdevmarcos commented on package.json
> +    "next-pwa": "^5.3.1",
remover next-pwa dos pacotes, nao vamos utilizar PWA nesse projeto.

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +  status?: string | undefined
```suggestion
  status?: string
```

quando voce passa o optinal `?` nao precisa passar o undefined.
O Typescript ja entende que quando voce passa o optional, a chave pode ser `undefined`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +    backgroundColor={notification ? '#D8F3FF' : '#fafeff'}
Colocar cores no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +          color="#0A0A0A"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +            <Icon as={BiMusic} w="1.8rem" h="1.8rem" color="#575a9b" />
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +          bg="#3BB2EA"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +          color="#FDFEFF"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +        <Flex bg="#FF3A45" borderRadius="50%" p="0.4rem">
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Contact.tsx
> +          <Icon as={BiBell} color="#fff" w="1.6rem" h="1.6rem" />
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/MyProfile.tsx
> +      bg="#FDFEFF"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/MyProfile.tsx
> +            color="#0A0A0A"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/MyProfile.tsx
> +        <Icon as={BiLogOut} w="2.4rem" h="2.4rem" color="#005683" />
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/components/Status.tsx
> +        ? '#F83737'
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +  const handleToggleOffline = () => setShowOffline(!showOffline)
```suggestion
  const handleToggleOnline = () => setShowOnline((prevState) => !prevState)
  const handleToggleOffline = () => setShowOffline((prevState) => !prevState)
```

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +    <Box backgroundColor="#f0f8ff" height="100vh">
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +        backgroundColor="#ffffff"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +            color="#0A0A0A"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +              color="#005683"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +            color="#0A0A0A"
Colocar cor no `theme`

2023-02-07 09:22 UTC, iamdevmarcos commented on src/pages/list.tsx
> +              color="#005683"
Colocar cor no `theme`

2023-02-09 00:23 UTC, Claytonrss approved these changes

2023-02-11 22:08 UTC, ander0308 commented on package.json
> +    "next-pwa": "^5.3.1",
concordo.

2023-02-11 22:08 UTC, ander0308 commented on src/components/Contact.tsx
> +        <Flex bg="#FF3A45" borderRadius="50%" p="0.4rem">
@iamdevmarcos No meu código, o fontWeight, estou seguindo esse padrão (fontWeight="600") qual o correto?

2023-02-11 22:10 UTC, ander0308 approved these changes

2023-02-11 22:19 UTC, iamdevmarcos approved these changes

2023-02-11 22:19 UTC, merged