Integrate ChatList to individual Chat
United-Devs/msn-client pull request #8
Opened 2023-02-12 13:12 UTC by iamdevmarcos

2023-02-12 13:21 UTC, milealmeida requested changes

2023-02-12 13:21 UTC, milealmeida commented on src/pages/list.tsx
>  import MyProfile from 'components/MyProfile'
Coloca o MyProfile e o Contact dentro de um index, para vir numa importação apenas

2023-02-12 13:21 UTC, milealmeida commented on src/pages/chat/[id].tsx
> +        <Profile
Esse Profile seria o equivalente ao MyProfile correto?? Se sim, escolhe um dos dois apenas, para não ficar dois componentes com a mesmas função

2023-02-12 13:51 UTC, iamdevmarcos commented on src/pages/list.tsx
>  import MyProfile from 'components/MyProfile'
Feito

2023-02-12 13:52 UTC, iamdevmarcos commented on src/pages/chat/[id].tsx
> +        <Profile
Sao duas coisas diferentes, pra facilitar eu mudei o nome de `Profile` para `UserInfo`

2023-02-12 14:12 UTC, milealmeida approved these changes

2023-02-14 00:46 UTC, ander0308 commented on src/components/ChatKeyboard.tsx
>          <Input
alterar a cor do hover do botão de enviar mensagem, ainda está pegando a antiga.

![image](https://user-images.githubusercontent.com/56742370/218608943-f8ce3aee-9cd4-4397-ad86-2ff42d8a4fc4.png)

2023-03-01 22:36 UTC, merged